/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsideRouteImport } from './routes/_inside'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsideTimelineRouteImport } from './routes/_inside.timeline'
import { Route as InsideMomentsRouteImport } from './routes/_inside.moments'
import { Route as InsideLetterRouteImport } from './routes/_inside.letter'
import { Route as InsideHomeRouteImport } from './routes/_inside.home'
import { Route as InsideGalleryRouteImport } from './routes/_inside.gallery'

const InsideRoute = InsideRouteImport.update({
  id: '/_inside',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsideTimelineRoute = InsideTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => InsideRoute,
} as any)
const InsideMomentsRoute = InsideMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => InsideRoute,
} as any)
const InsideLetterRoute = InsideLetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => InsideRoute,
} as any)
const InsideHomeRoute = InsideHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => InsideRoute,
} as any)
const InsideGalleryRoute = InsideGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => InsideRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof InsideGalleryRoute
  '/home': typeof InsideHomeRoute
  '/letter': typeof InsideLetterRoute
  '/moments': typeof InsideMomentsRoute
  '/timeline': typeof InsideTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof InsideGalleryRoute
  '/home': typeof InsideHomeRoute
  '/letter': typeof InsideLetterRoute
  '/moments': typeof InsideMomentsRoute
  '/timeline': typeof InsideTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_inside': typeof InsideRouteWithChildren
  '/_inside/gallery': typeof InsideGalleryRoute
  '/_inside/home': typeof InsideHomeRoute
  '/_inside/letter': typeof InsideLetterRoute
  '/_inside/moments': typeof InsideMomentsRoute
  '/_inside/timeline': typeof InsideTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gallery' | '/home' | '/letter' | '/moments' | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gallery' | '/home' | '/letter' | '/moments' | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/_inside'
    | '/_inside/gallery'
    | '/_inside/home'
    | '/_inside/letter'
    | '/_inside/moments'
    | '/_inside/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsideRoute: typeof InsideRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_inside': {
      id: '/_inside'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof InsideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inside/timeline': {
      id: '/_inside/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof InsideTimelineRouteImport
      parentRoute: typeof InsideRoute
    }
    '/_inside/moments': {
      id: '/_inside/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof InsideMomentsRouteImport
      parentRoute: typeof InsideRoute
    }
    '/_inside/letter': {
      id: '/_inside/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof InsideLetterRouteImport
      parentRoute: typeof InsideRoute
    }
    '/_inside/home': {
      id: '/_inside/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof InsideHomeRouteImport
      parentRoute: typeof InsideRoute
    }
    '/_inside/gallery': {
      id: '/_inside/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof InsideGalleryRouteImport
      parentRoute: typeof InsideRoute
    }
  }
}

interface InsideRouteChildren {
  InsideGalleryRoute: typeof InsideGalleryRoute
  InsideHomeRoute: typeof InsideHomeRoute
  InsideLetterRoute: typeof InsideLetterRoute
  InsideMomentsRoute: typeof InsideMomentsRoute
  InsideTimelineRoute: typeof InsideTimelineRoute
}

const InsideRouteChildren: InsideRouteChildren = {
  InsideGalleryRoute: InsideGalleryRoute,
  InsideHomeRoute: InsideHomeRoute,
  InsideLetterRoute: InsideLetterRoute,
  InsideMomentsRoute: InsideMomentsRoute,
  InsideTimelineRoute: InsideTimelineRoute,
}

const InsideRouteWithChildren =
  InsideRoute._addFileChildren(InsideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsideRoute: InsideRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
